### PR TITLE
Share module

### PR DESCRIPTION
**Pull request by miceno**
Based on the skeleton of the Facebook share module but using AddThis library.

### CODE REVIEW

**Comment by dakanji** [comment]
Difficult to see what is going on due to the large number of files showing as changed because of the branch merge.

You can rebase instead to avoid these in future.

If you prefer a standard merge as done here, please squash the commits into one before making the PR. For this case, you can still squash and then force push afterwards. I gave the steps needed here in case you need this: https://github.com/dakanji/G2Project-modules/pull/3#issuecomment-456948350

**Comment by dakanji** [comment]
I had since started the process of moving some modules to main.

I will clean this PR up later

**Comment by miceno** [comment]
Hi, I squashed my commits and left yours as they were... I am not very proficient on contributing to open source projects, so my apologies if this is not the way.

The point is that when I try to sync `upstream` with my local, I do it by `merge` strategy, and there are usually conflicts, so I solve them. If it is better to use `rebase` strategy for this, I will use it. 

But case of `rebase`, do the resolution of conflicts on files you changed impact the `dev` branch? Will then it become a mess? ;)

**Comment by dakanji** [comment]
Hi,

Never mind. I cherry picked the relevant commit.

The conflicts were mainly because of style changes. These will settle down now and should be fewer in between. 

You can continue with what works for you in terms of Merging / Rebasing. There is no right or wrong. However, I personally think using rebase to keep a forked branch up to date is cleaner.

In this case, you had `feature/share`
> $ git checkout feature/share
> $ git rebase upstream/dev

If you have conflicts, they will only apply to your commits in this case and after you resolve them, you use ...
> $ git rebase --continue.

Are you using a git client?

**Comment by miceno** [comment]
Thank you for the guidelines.

The point is that my workflow is as follows:

1. First I pull dakanji/G2Project-modules/dev-modules into miceno/G2Project-modules/dev-modules
2. Then I checkout to my feature branch
3. Then I merge miceno/G2Project-modules/dev-modules into my feature branch.

I do it this way so I can branch locally from miceno/G2Project-modules/dev-modules, and I always have a fresh miceno/G2Project-modules/dev-modules to start with. 

I will use rebase on steps 1 and 3.

I am using SourceTree for MacOS.

Regards.
--
"El camino del Tao es muy recto y directo; pero a la gente le encantan las carreteras secundarias"    extracto del capítulo 53 del Tao Te Ching
Orestes Sanchez Benavente         orestes@estotienearreglo.es

**Comment by dakanji** [comment]
Hi,

I follow the same process for forked repos. Only point of note is that I never locally merge back into local/dev branch (even for items where my PR is accepted) so that it is always consistent with  upstream/dev. The rebase is therefore only needed for Step 3.

To update origin/dev, I pull upstream/dev to local/dev and then push local/dev to origin/dev.

Btw, I asked about the Git client because of your question about the impact of rebasing on dev as I also use sourcetree and I thought you probably do the same as the way they have labelled the rebase context menu is upside down and confusing. 

Basically leads people to think they will change a branch (such as dev) when what it intends to say is that it will take the changes from that branch. There is a l[ong standing issue raised about this](https://jira.atlassian.com/browse/SRCTREE-1578?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true) which they have failed to address. 

In the end, I find the commandline clearer and better for certain actions. Obviously also far more flexible and so, I tend to also use this quite a bit.

As said though, whatever works for you is fine. One tip I found with sourcetree is NOT to tick the checkbox that says something like "merge commit immediately", or similar, when merging.

**Pull request closed without merging**
